config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'landing#index'
  get 'stats/users', to: 'stats#users'
  get 'stats', to: 'stats#index'
  get 'tests/index'

  post 'locations/nearby', to: 'locations#nearby'
  get 'locations/hot', to: 'locations#hot'

  get ':building_id/reviews', to: 'reviews#index'
  post ':building_id/reviews', to: 'reviews#create'

  post 'visited', to: 'users#visited'
  get 'winners', to: 'users#winners'
  get '/claims/:user_id', to: 'users#claim', as: 'claim_path'

  get 'locations', to: 'locations#index'

  get 'assistances', to: 'assistances#index'
  get 'assistances_page', to: 'assistances#index_html'
  get 'assistances/:user_id', to: 'assistances#show'
  post 'assistance', to: 'assistances#create'
  delete 'assistance/:user_id', to: 'assistances#destroy'

  get 'assistance/maps', to: 'assistance_maps#index'
  get 'assistance/:user_id/location', to: 'assistances#user_location'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/assistance.rb
class Assistance < ApplicationRecord
  validates :user_id, uniqueness: true
end

app/models/location.rb
class Location < ApplicationRecord
  acts_as_mappable  :lat_column_name => :latitude,
                    :lng_column_name => :longitude

  validates :latitude,
            :longitude,
            presence: true

  has_many :reviews, dependent: :destroy
  has_many :visits
  has_many :users, through: :visits

  def self.to_csv
    CSV.generate do |csv|
      csv << column_names
      all.each do |product|
        csv << product.attributes.values_at(*column_names)
      end
    end
  end
end

app/models/review.rb
class Review < ApplicationRecord
  validates :body,
            :user_name,
            presence: true

  belongs_to :location
end

app/models/user.rb
class User < ApplicationRecord
  has_many :visits
  has_many :locations, through: :visits
end

app/models/visit.rb
class Visit < ApplicationRecord
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def index
  end
end

app/controllers/locations_controller.rb
# API endpoints for Locations

class LocationsController < ApplicationController
  skip_before_action :verify_authenticity_token

  def nearby
    closest = Location.closest(:origin => [params[:latitude], params[:longitude]])
    locations = Location.within(1.0, :origin => [params[:latitude], params[:longitude]]).where.not(id: closest.first.id).limit(5)
    hot_locations = Location.all.where.not(visited_num: nil).order('visited_num DESC').limit(4)

    if closest.first.present?
      closest.first.increment!(:visited_num)
    end

    hot_string = ""
    if hot_locations.present?
      hot_locations.each do |location|
        if hot_string == ""
          hot_string = hot_string + "h||#{location.name}||#{location.description}"
        else
          hot_string = hot_string + "||h||#{location.name}||#{location.description}"
        end
      end
      hot_string = "||" + hot_string + "^&"
    end
    string = ""
    if locations.present?
      locations.each do |location|
        if string == ""
          string = string + "n||#{location.name}||#{location.description}"
        else
          string = string + "||n||#{location.name}||#{location.description}"
        end
      end
    end
    closest_string = "~@c||#{closest.first.id}||#{closest.first.name}||#{closest.first.description}"
    new_string = "#{closest_string}||#{string}#{hot_string}"
    render plain: new_string
  end

  def hot
    hot_locations = Location.all.where.not(visited_num: nil).order('visited_num DESC').limit(4)
    string = ""
    if hot_locations.present?
      hot_locations.each do |location|
        if string == ""
          string = string + "location%||#{location.name}||#{location.description}"
        else
          string = string + "||location%||#{location.name}||#{location.description}"
        end
      end
      string = "~@" + string + "^&"
    end
    render plain: string
  end

  def index
    @locations = Location.all.order(:id)
    render json: @locations, only: [:id, :name, :latitude, :longitude, :description, :visited_num]
  end
end

app/controllers/reviews_controller.rb
# API endpoints for reviews

class ReviewsController < ApplicationController
  skip_before_action :verify_authenticity_token

  def index
    location = Location.find(params[:building_id])
    reviews = location.reviews.order("created_at DESC").limit(6)
    string = ""
    if reviews.present?
      reviews.each do |review|
        if string == ""
          string = string + "r||#{review.user_name}||#{review.body}"
        else
          string = string + "||r||#{review.user_name}||#{review.body}"
        end
      end
      string = "~@" + string + "^&"
    end
    render plain: string
  end

  def create
    location = Location.find(params[:building_id])
    review = location.reviews.build(body: params[:review], user_id: params[:user_id], user_name: params[:user_name])
    review.save!
    render plain: "~@success||DonaldTrumpWasHere||^&"
  end
end

app/controllers/stats_controller.rb
class StatsController < ApplicationController
  def index
    @locations = Location.all.order(:id)
    @reviews = Review.all.order(:id)
  end

  def users
    @users = User.all
  end
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
  def index
    string = "~@c||1||MacLeod Building||Where the smart people are at||n||Engineering Student Centre||CHEEZE||n||MacLeod Building||Where the smart people are at||n||MacMillan Building||Farmers???||n||ICICS||Cool guys are here||h||MacLeod Building||Where the smart people are at||h||MacMillan Building||Farmers???||h||ICICS||Cool guys are here||h||Engineering Student Centre||CHEEZE||h||ICICS||Cool guys are here||h||Engineering Student Centre||CHEEZE||h||ICICS||Cool guys are here||h||Engineering Student Centre||CHEEZE||h||ICICS||Cool guys are here||h||Engineering Student Centre||CHEEZE||h||ICICS||Cool guys are here||h||Engineering Student Centre||CHEEZE^&"
    render text: string
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :verify_authenticity_token

  def visited
    if params[:user_id].empty?
      params[:user_id] = 1
    end
    id = params[:location_id].to_i - 1
    @user = User.find_or_create_by(id: params[:user_id])
    if @user.visits.where(location_id: params[:location_id], user_id: params[:user_id]).empty?
      @user.visits.build(user_id: params[:user_id], location_id: params[:location_id])
      @user.save
    end
    if @user.visits.where(location_id: 1).present? && @user.visits.where(location_id: 5).present?
      render plain: 'Congratulations! You have won a prize, visit the visitor information center to claim it!'
    elsif @user.visits.where(location_id: 1).present? && @user.visits.where(location_id: 5).empty?
      render plain: 'You need to visit Pharmacy building to be eligible for a prize.'
    elsif @user.visits.where(location_id: 1).empty? && @user.visits.where(location_id: 5).present?
      render plain: 'You need to visit MacLeod building to be eligible for a prize.'
    else
      render plain: 'Visit Pharmacy building and MacLeod building to be eligible for a prize!'
    end
  end

  def winners
    @users = User.all
    @winners = []
    @users.each do |user|
      if user.visits.where(location_id: 1).present? && user.visits.where(location_id: 5).present?
        @winners.push(user)
      end
    end
  end

  def claim
    @user = User.find(params[:user_id])
    @user.visits.first.update_column(:claimed, true)
    redirect_to winners_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assistance_maps_helper.rb
module AssistanceMapsHelper
end

app/helpers/assistances_helper.rb
module AssistancesHelper
end

app/helpers/coordinates_helper.rb
module CoordinatesHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/stats_helper.rb
module StatsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/landing/index.html.erb
<div class="text-center" id="background">
  <div class="title">Ware2GO Admin Panel</h2>
  <div class="text-center padding-top lg">
    <div class="btn-group-vertical btn-group-lg">
      <%= link_to 'Users View', stats_users_path, class: 'btn btn-success' %>
      <div class="margin-top lg"></div>
      <%= link_to 'Statistics', stats_path, class: 'btn btn-success' %>
      <div class="margin-top lg"></div>
      <%= link_to 'Assistance Requests', assistances_page_path, class: 'btn btn-success' %>
      <div class="margin-top lg"></div>
      <%= link_to 'Assistance Map', assistance_maps_path, class: 'btn btn-success' %>
      <div class="margin-top lg"></div>
      <%= link_to 'Prize Winners', winners_path, class: 'btn btn-success' %>
    </div>
  </div>
</div>

app/views/stats/index.html.erb
<h2 class="text-center">Ware2GO Statistics</h2>

<div class="container">
  <div class="row">
    <div class="col-lg-6">
      <table class="table">
        <thead class="thead-inverse">
          <tr>
            <th>Location #</th>
            <th>Location Name</th>
            <th>Location Description</th>
            <th># of Visitors</th>
          </tr>
        </thead>
        <tbody>
          <% @locations.each do |location| %>
            <tr>
              <td><%= location.id %></td>
              <td><%=location.name %></td>
              <td><%=location.description %></td>
              <td><%=location.visited_num %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="col-lg-6">
      <table class="table">
        <thead class="thead-inverse">
          <tr>
            <th>Review #</th>
            <th>User ID</th>
            <th>User Name</th>
            <th>Location ID</th>
            <th>Review</th>
          </tr>
        </thead>
        <tbody>
          <% @reviews.each do |review| %>
            <tr>
              <td><%= review.id %></td>
              <td><%= review.user_id %></td>
              <td><%= review.user_name %></td>
              <td><%= review.location_id %></td>
              <td><%= review.body %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/stats/users.html.erb
<h2 class="text-center">Users View</h2>
<div class="container">
  <table class="table">
    <thead class="thead-inverse">
      <tr>
        <th>User #</th>
        <th>Last visited location</th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.id %></td>
          <% if user.visits.present? %>
            <td><%= Location.find(user.visits.first.location_id).name %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>